### ISSUE TITLE
Code Not Working

### ISSUE THREAD

**Issue by iraunit** [yyysjz1997/SGDP#1]
The data_preprocess.py file is not generating the required CSV file. Could you give me the generated CSV file or the complete code.

**Comment by yyysjz1997** [comment]
> The data_preprocess.py file is not generating the required CSV file. Could you give me the generated CSV file or the complete code.

Hi! Thanks for your interest for our work. You can download all datasets from [there](http://iotta.snia.org/traces/block-io/388).

**Comment by iraunit** [comment]
I downloaded the dataset of 3 GB, but cannot understand which is the required dataset that data_preprocess.py will be generating. Can you explain me or give me the csv file that data_preprocess.py will be generating?

**Comment by yyysjz1997** [comment]
> I downloaded the dataset of 3 GB, but cannot understand which is the required dataset that data_preprocess.py will be generating. Can you explain me or give me the csv file that data_preprocess.py will be generating?

    if opt.type =='full' or opt.type =='8k':
        dataset_dir = '../data/datasets_by_type/'
        for type_dir in os.listdir(dataset_dir):
                print(type_dir)
                if type_dir =='VDI512':
                    dataset_type_dir = os.path.join(dataset_dir,type_dir)
                    for trace_name in os.listdir(dataset_type_dir):
                        trace_path = os.path.join(dataset_type_dir,trace_name)
                        print('processing original trace to 8klba trace, trace name:',trace_path)
                        # trace_type = type_dir.split('/')[-2]
                        trace_to_8k(trace_path=trace_path,trace_type=type_dir)

../data/datasets_by_type/ is the base_dir, and just download dataset there, data_preprocess.py will automatically preprocess the data (split space 8K or 64M). There are more description about experiments and detailed implementations in paper V.D. Implementation Details. If you get something wrong, please change your bass_dir. Thanks!
