### ISSUE TITLE
Inquiry about the code for stride prefetcher

### ISSUE THREAD

**Issue by faradawn** [yyysjz1997/SGDP#2]
Hi,

May I ask is there a code for stride prefetcher as described as 

“Stride Prefetcher [6] simultaneously records 128 LBA access streams, and each of them tracks the last 3 LBA accesses. Each access is mapped to a stream based on hashing the most significant LBA. If the difference between the 3 LBA accesses matches, it will detect a stride and conduct a prediction.” 

Would really like to compare the stride prefetcher as a baseline model. Thanks very much!

**Comment by yyysjz1997** [comment]
> Hi,
> 
> May I ask is there a code for stride prefetcher as described as
> 
> “Stride Prefetcher [6] simultaneously records 128 LBA access streams, and each of them tracks the last 3 LBA accesses. Each access is mapped to a stream based on hashing the most significant LBA. If the difference between the 3 LBA accesses matches, it will detect a stride and conduct a prediction.”
> 
> Would really like to compare the stride prefetcher as a baseline model. Thanks very much!

Hello. I'm very sorry, but due to a lone time, the code for Stride prefetcher that I reproduced at the time can no longer be found. You can reproduce it yourself according to our description. Thank you for your interest, and feel free to cite it.

Beside, there is a chatgpt reproduced Stride prefetcher, FYI.
`class StridePrefetcher:
    def __init__(self, num_streams=128, history_size=3):
        self.num_streams = num_streams
        self.history_size = history_size
        self.streams = {}
        
    def map_to_stream(self, lba):
        # Hash the most significant LBA to determine the stream index
        stream_index = hash(lba) % self.num_streams
        if stream_index not in self.streams:
            self.streams[stream_index] = [lba]
        else:
            self.streams[stream_index].append(lba)
        
        # Check for stride prediction
        if len(self.streams[stream_index]) >= self.history_size:
            last_accesses = self.streams[stream_index][-self.history_size:]
            if all(last_accesses[i] - last_accesses[i-1] == last_accesses[1] - last_accesses[0] for i in range(1, self.history_size)):
                # Detected a stride, perform prefetching or prediction here
                print("Detected a stride:", last_accesses)

# Create a StridePrefetcher
prefetcher = StridePrefetcher()

# Simulate LBA accesses
lba_accesses = [100, 105, 110, 200, 205, 300, 400, 405, 500]
for lba in lba_accesses:
    prefetcher.map_to_stream(lba)`

**Comment by faradawn** [comment]
Hi @yyysjz1997,

Thank you so such a prompt reply! I check the GPT implementation and reference your paper's description. 

Will cite this paper when we use the stride prefetcher as a baseline.

Thanks,
Faradawn
